/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Negocio.Conexion;
import Negocio.OpcionesTabla;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;

/**
 *
 * @author MATEO
 */
public class JFMenuCine extends javax.swing.JFrame {

    Conexion con;
    OpcionesTabla operacionesTabla;
    
    public JFMenuCine() {
        initComponents();
        setIconImage(getIconImage());
        con = new Conexion();
        operacionesTabla = new OpcionesTabla();
        this.setLocationRelativeTo(this);
        
    }
    @Override
    public Image getIconImage() 
    {
        Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/conexion.png"));
        return icono;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBCliente = new javax.swing.JButton();
        jBAsientos = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jBTicket = new javax.swing.JButton();
        jBSala = new javax.swing.JButton();
        jBPelicula = new javax.swing.JButton();
        jBAsientoSala = new javax.swing.JButton();
        jBSalaPelicula = new javax.swing.JButton();
        jBCineUsuari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINE");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones del CINE"));

        jLabel1.setFont(new java.awt.Font("Farsan", 0, 36)); // NOI18N
        jLabel1.setText("Escoja una de las siguientes opciones");

        jBCliente.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/objetivo.png"))); // NOI18N
        jBCliente.setText("Cliente");
        jBCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCliente.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBCliente.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBClienteActionPerformed(evt);
            }
        });

        jBAsientos.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBAsientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/asiento-de-cine.png"))); // NOI18N
        jBAsientos.setText("Asientos");
        jBAsientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAsientos.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBAsientos.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsientosActionPerformed(evt);
            }
        });

        jBSalir.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBSalir.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBTicket.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/museo.png"))); // NOI18N
        jBTicket.setText("Ticket");
        jBTicket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBTicket.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBTicket.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTicketActionPerformed(evt);
            }
        });

        jBSala.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pantalla-de-cine.png"))); // NOI18N
        jBSala.setText("Sala");
        jBSala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSala.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBSala.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalaActionPerformed(evt);
            }
        });

        jBPelicula.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula.png"))); // NOI18N
        jBPelicula.setText("Película");
        jBPelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBPelicula.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBPelicula.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPeliculaActionPerformed(evt);
            }
        });

        jBAsientoSala.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBAsientoSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pantalla-de-cine.png"))); // NOI18N
        jBAsientoSala.setText("Asiento - Sala");
        jBAsientoSala.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAsientoSala.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBAsientoSala.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBAsientoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAsientoSalaActionPerformed(evt);
            }
        });

        jBSalaPelicula.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBSalaPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pelicula.png"))); // NOI18N
        jBSalaPelicula.setText("Sala - Película");
        jBSalaPelicula.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBSalaPelicula.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBSalaPelicula.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBSalaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalaPeliculaActionPerformed(evt);
            }
        });

        jBCineUsuari.setFont(new java.awt.Font("Rum Raisin", 0, 14)); // NOI18N
        jBCineUsuari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pareja.png"))); // NOI18N
        jBCineUsuari.setText("Menú usuario");
        jBCineUsuari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBCineUsuari.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jBCineUsuari.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jBCineUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCineUsuariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jBSalaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jBTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(jBPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jBSala, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117)
                                .addComponent(jBCineUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jBAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(jBAsientoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(226, 226, 226)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSala, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAsientoSala, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBSalaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCineUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jBClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBClienteActionPerformed
        JFPersona jfpersona = new JFPersona();
        jfpersona.setVisible(true);
    }//GEN-LAST:event_jBClienteActionPerformed

    private void jBAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsientosActionPerformed
        JFAsiento jfasientos = new JFAsiento();
        jfasientos.setVisible(true);
    }//GEN-LAST:event_jBAsientosActionPerformed

    private void jBTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTicketActionPerformed
        JFTicket jfticket = new JFTicket();
        jfticket.setVisible(true);
    }//GEN-LAST:event_jBTicketActionPerformed

    private void jBSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalaActionPerformed
        JFSala jfsala = new JFSala();
        jfsala.setVisible(true);
    }//GEN-LAST:event_jBSalaActionPerformed

    private void jBPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPeliculaActionPerformed
        JFPelicula jfpeli = new JFPelicula();
        jfpeli.setVisible(true);
    }//GEN-LAST:event_jBPeliculaActionPerformed

    private void jBAsientoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAsientoSalaActionPerformed
        JFAsientoSala jfasientoSala = new JFAsientoSala();
        jfasientoSala.setVisible(true);
    }//GEN-LAST:event_jBAsientoSalaActionPerformed

    private void jBSalaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalaPeliculaActionPerformed
        JFSalaPelicula jfsalaPeli = new JFSalaPelicula();
        jfsalaPeli.setVisible(true);
    }//GEN-LAST:event_jBSalaPeliculaActionPerformed

    private void jBCineUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCineUsuariActionPerformed
        JFCineUsuario jfmenuUsuario = new JFCineUsuario();
        jfmenuUsuario.setVisible(true);
    }//GEN-LAST:event_jBCineUsuariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMenuCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMenuCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMenuCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMenuCine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMenuCine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAsientoSala;
    private javax.swing.JButton jBAsientos;
    private javax.swing.JButton jBCineUsuari;
    private javax.swing.JButton jBCliente;
    private javax.swing.JButton jBPelicula;
    private javax.swing.JButton jBSala;
    private javax.swing.JButton jBSalaPelicula;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jBTicket;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
